# Generated by Django 3.2.7 on 2021-10-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegistrationRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.CharField(blank=True, max_length=100, null=True)),
                ('building_name', models.CharField(blank=True, max_length=300, null=True)),
                ('street_name', models.CharField(blank=True, max_length=300, null=True)),
                ('landmark', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_front_photo', models.CharField(blank=True, max_length=1010, null=True)),
                ('aadhaar_back_photo', models.CharField(blank=True, max_length=1010, null=True)),
                ('licence_front_photo', models.CharField(blank=True, max_length=1010, null=True)),
                ('licence_back_photo', models.CharField(blank=True, max_length=1010, null=True)),
                ('passport_size_photo', models.CharField(blank=True, max_length=1100, null=True)),
                ('vehicle_RTO_registration_number', models.CharField(blank=True, max_length=1010, null=True)),
                ('vehicle_rc_number', models.CharField(blank=True, max_length=400, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make_year', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('global_vehicle_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_front_photo', models.CharField(blank=True, max_length=600, null=True)),
                ('vehicle_back_photo', models.CharField(blank=True, max_length=600, null=True)),
                ('vehicle_left_photo', models.CharField(blank=True, max_length=600, null=True)),
                ('vehicle_right_photo', models.CharField(blank=True, max_length=600, null=True)),
                ('request_token', models.CharField(blank=True, max_length=1100, null=True)),
                ('status', models.CharField(blank=True, max_length=110, null=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('vehicle_brand', models.CharField(blank=True, max_length=1200, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=1200, null=True)),
                ('account_verification_status', models.CharField(blank=True, max_length=450, null=True)),
                ('pan_card', models.CharField(blank=True, max_length=600, null=True)),
                ('vehicle_rc', models.CharField(blank=True, max_length=600, null=True)),
                ('vehicle_insurance', models.CharField(blank=True, max_length=1000, null=True)),
                ('vehicle_permit', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_deliver_partner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
