# Generated by Django 3.2.7 on 2021-10-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverRegistrationRequestModel',
            new_name='driver_registartion_request',
        ),
    ]
