# Generated by Django 3.2.7 on 2021-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_driverregistrationrequestmodel_driver_registartion_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='is_deliver_partner',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='pan_card',
            field=models.CharField(blank=True, max_length=445, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='vehicle_RTO_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='vehicle_insurance',
            field=models.CharField(blank=True, max_length=445, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='vehicle_permit',
            field=models.CharField(blank=True, max_length=445, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registartion_request',
            name='vehicle_rc',
            field=models.CharField(blank=True, max_length=445, null=True),
        ),
    ]
